name: funny
favicon: null
layout_spectrum: 0.33992164372466505
typography_spectrum: 0.38044658163562417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7310659394133836
  lightness: 0.8356670283246785
  saturation: 0.270938090281561
  rhythmicContrast: 0.0293324152007699
purpose: []
